name: Create pull request

on:
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Rub build
      run: dotnet build --no-restore
      
    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Run linter
      uses: super-linter/super-linter@v5
      env:
       DEFAULT_WORKSPACE: WebAPI/WebAPI.csproj
       DEFAULT_BRANCH: master
       VALIDATE_ALL_CODEBASE: true
       VALIDATE_DOTNET_DOTNET_FORMAT: true
       VALIDATE_YAML: false
       GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
