name: Build ASP.Net Core apps

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Rub build
      run: dotnet build --no-restore
      
    - name: Run publish
      run: dotnet publish WebAPI/WebAPI.csproj -c Release -o app

    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.3
      with:
       name: app
       path: app

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download artifact
        uses: actions/download-artifact@v3

      - name: Setup SSH
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 -t ed25519 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Stop application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            export XDG_RUNTIME_DIR=/run/user/$(id -u)
            systemctl --user stop app.service

      - name: Deploy to server
        run: |
          rsync -azP -e "ssh -i $HOME/.ssh/id_ed25519 -p 22" ./app ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/

      - name: Start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            export XDG_RUNTIME_DIR=/run/user/$(id -u)
            systemctl --user start app.service
