name: Build ASP.Net Core apps

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'
        include-prerelease: true
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish WebAPI/WebAPI.csproj -c Release -o app

    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.3
      with:
       name: app
       path: app

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v2
          
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: root
          server: ${{secrets.SSH_HOST}}
          port: 22
          ssh_private_key: ${{secrets.SSH_KEY}}
 
          
          # will put all file under this path
          local_path: ./* # default is ./*
          # files will copy to under remote_path
          remote_path: /var/www
          
          # sftp args
          args: '-o ConnectTimeout=5'


        
